SELECT 
 ROW_NUMBER(INTERFACE_HEADER_ID), 
 1 BATCH_ID,
 'CARGA_TEST' IMPORT_SOURCE,
  NULL as APPROVAL_ACTION,
  'BLANKET' DOCUMENT_TYPE_CODE, 
  NULL as STYLE_ID,
  NULL as PRC_BU_NAME,
  NULL as AGENT_NAME,
  NULL as CURRENCY_CODE,
 'SUMMUM PROJECTS S.A.' VENDOR_NAME,
  NULL as SUPPLIER_NUMBER,
  NULL as SUPPLIER_SITE,
  NULL as SUPPLIER_CONTACT,
  NULL as SUPPLIER_ORDER, 
  NULL as FOD,
  NULL as CARRIER,
  NULL as FREIGHT_TERMS, 
  NULL as PAY_ON_CODE,
  NULL as PAYMENT_TERMS,
  NULL as INITIATING_PARTY,
 'Actualizacion flag' CHANGE_ORDER_DESC,
-- H. NULL --Required_Acknowledgment,
  NULL ACCEPTANCE_WITHIN_DAYS,
-- H. NULL  --Communication_Method
  NULL as FAX,   
  NULL as EMAIL_ADDRESS,
  NULL as CONFIRMING_ORDER_FLAG,
  NULL as AMOUNT_AGREED,
  NULL as AMOUNT_LIMIT,
  NULL as MIN_RELEASE_AMOUNT,
  NULL as START_DATE,
  NULL as CLOSED_DATE,
  NULL as NOTE_TO_VENDOR,
  NULL as NOTE_TO_RECEIVER,
  NULL as GENERATE_ORDERS_AUTOMATIC,
  NULL as SUBMIT_APPROVAL_AUTOMATIC
FROM POZ_SUPPLIERS_V S
JOIN PO_HEADERS_ALL H
ON S.VENDOR_ID = H.VENDOR_ID
JOIN HR_ORGANIZATION_UNITS_F_TL T
ON T.ORGANIZATION_ID = H.PRC_BU_ID
WHERE T.LANGUAGE = 'E';